## S03 T04: Pràctica amb programació numèrica

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [36]:
import numpy as np

#First, we need to apply the condition to exclude non 1D arrays, we use the if clause.
#If array complies with condition, then average, variance and std deviation is calculated thru numpy methods
#I've rounded the result up to 2 decimals

def estadisticaArray(arr):
    
    if np.ndim(arr)!=1:
        print("L'array ha de tenir una dimensió")
    else:
        mitjana=np.average(arr)
        print("La mitjana d'aquest array és", np.around(mitjana,2))
        varian=np.var(arr)
        print("La variança d'aquest array és", np.around(varian,2))
        desv_st=np.std(arr)
        print("La desviació estàndard d'aquest array és", np.around(desv_st,2))

#let's test our method with an example

arr=np.array([[1,3,8]])
estadisticaArray(arr)

L'array ha de tenir una dimensió


In [37]:
arr=np.array([1,3,8,5])
estadisticaArray(arr)

La mitjana d'aquest array és 4.25
La variança d'aquest array és 6.69
La desviació estàndard d'aquest array és 2.59


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [38]:
#First, import random from numpy
#using random.randint method to create the NxN square, random.randint(range of random numbers,size=(rows, columns)
#In this case N is any integer

from numpy import random

def quadrat_aleatori(N):
    arr=random.randint(100,size=(N,N))
    return arr

quadrat_aleatori(5)

array([[29, 30, 30, 51, 13],
       [82, 75, 51, 57, 97],
       [36, 45,  1, 16, 58],
       [52, 19, 26, 30, 85],
       [82, 77, 46, 73, 36]])

In [39]:
quadrat_aleatori(2)

array([[63, 14],
       [32, 26]])

### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [40]:
#we use .sum method for calculating the addition of all elements in rows and columns,
#(being axis=0, columns and axis1=rows)

def totals(arr):
    suma_columnes=arr.sum(axis=0)
    print("El total de les columnes és",suma_columnes)
    suma_fileres=arr.sum(axis=1)
    print("El total de les fileres és",suma_fileres)

In [41]:
#by creating an array of 2D we can apply the method created

arr = random.randint(10, size=(4, 5))
print(arr)
totals(arr)

[[8 4 4 6 7]
 [5 5 3 4 8]
 [0 2 3 4 4]
 [3 2 3 0 5]]
El total de les columnes és [16 13 13 14 24]
El total de les fileres és [29 25 13 13]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [42]:
#the formula for correlation coefficient is as follows: 
#r = Σᵢ((xᵢ − mean(x))(yᵢ − mean(y))) (√Σᵢ(xᵢ − mean(x))² √Σᵢ(yᵢ − mean(y))²)⁻¹

def coeficient_correlacio(X,Y):

    numerador = np.sum((X-np.mean(X))*(Y-np.mean(Y)))
    denominador = np.sqrt(np.sum((X-np.mean(X))**2))*np.sqrt(np.sum((Y-np.mean(Y))**2))
    return (numerador/denominador)                                                                                          

In [30]:
#test the function with a real life example:

#X represents variable "age"
X=np.array([20,30,40,50,60])

#Y represents variable "salary"
Y=np.array([15000,25000,35000,40000,42000])

#applying the function
coeficient_correlacio(X,Y)

0.9669519493078381

The result indicates a positive correlation between age and salary

In [31]:
#Now, let's try the build in numpy method corrcoef

np.corrcoef(X,Y)

array([[1.        , 0.96695195],
       [0.96695195, 1.        ]])

Corrcoef returns the correlation matrix, which is a two-dimensional array with the correlation coefficients.
he values on the main diagonal of the correlation matrix (upper left and lower right) are equal to 1. The upper left value corresponds to the correlation coefficient for x and x, while the lower right value is the correlation coefficient for y and y. They are always equal to 1.

What is needed are the lower left and upper right values that represent the Pearson correlation coefficient and that in this case matches with the function that I've created (0,9669)